class Art

  def self.title
    puts "               @@@@@@    @@@@@@@@@@@@@@@@   .@@@@@@@@@@@@@@@@   &@@@@@@@@@@@@@@@.      @@@@@@@@@@@       @@@@@@@@@@@@@@@@,    #@@@@@@@@@@@@@@@   /@@@@@(     @@@@@@   @@@@@  ".light_yellow
    puts "               @@@@@@   @@@@@@@@@@@@@@@@@   @@@@@@@@@@@@@@@@@   &@@@@@@@@@@@@@@@@*    @@@@@@@@@@@@&      @@@@@@@@@@@@@@@@@*   #@@@@@@@@@@@@@@@@. /@@@@@(     @@@@@@   @@@@@  ".light_yellow
    puts "               @@@@@@   @@@@@@@@@@@@@@@@@   @@@@@@@@@@@@@@@@@   &@@@@@@@@@@@@@@@@/    @@@@@@@@@@@@@      @@@@@@@@@@@@@@@@@*   #@@@@@@@@@@@@@@@@. /@@@@@(     @@@@@@   @@@@@  ".light_yellow
    puts "               @@@@@@   @@@@@@@@@@@@@@@@@   @@@@@@@@@@@@@@@@@   &@@@@@@@@@@@@@@@@/   .@@@@@@@@@@@@@      @@@@@@@@@@@@@@@@@*   #@@@@@@@@@@@@@@@@. /@@@@@(     @@@@@@   @@@@@  ".light_yellow
    puts "               @@@@@@   @@@@@@@@@@@@@@@@@   @@@@@@@@@@@@@@@@@   &@@@@@@@@@@@@@@@@/   #@@@@@@@@@@@@@,     @@@@@@@@@@@@@@@@@*   #@@@@@@@@@@@@@@@@. /@@@@@(     @@@@@@   @@@@@  ".light_yellow
    puts "               @@@@@@   @@@@@@@@@@@@@@@@@   @@@@@@@@@@@@@@@@@   &@@@@@@@@@@@@@@@@/   @@@@@@@@@@@@@@@     @@@@@@@@@@@@@@@@@*   #@@@@@@@@@@@@@@@@. /@@@@@(     @@@@@@   @@@@@  ".light_yellow
    puts "               @@@@@@   @@@@@@@@@@@@@@@@@   @@@@@@@@@@@@@@@@@   &@@@@@@@@@@@@@@@@/   @@@@@@@@@@@@@@@     @@@@@@@@@@@@@@@@@*   #@@@@@@@@@@@@@@@@. /@@@@@(     @@@@@@   @@@@@  ".light_yellow
    puts "               @@@@@@   @@@@@@@@@@@@@@@@@   @@@@@@@@@@@@@@@@@   &@@@@@@@@@@@@@@@@/   @@@@@@@@@@@@@@@     @@@@@@@@@@@@@@@@@*   #@@@@@@@@@@@@@@@@. /@@@@@(     @@@@@@   @@@@@  ".light_yellow
    puts "               @@@@@@   @@@@@@,             @@@@@@(    @@@@@@   &@@@@@/    %@@@@@/  *@@@@@@   @@@@@@,    @@@@@@     @@@@@@*   #@@@@@      @@@@@. /@@@@@(     @@@@@@   @@@@@  ".light_yellow
    puts "               @@@@@@   @@@@@@,             @@@@@@(    @@@@@@   &@@@@@/    %@@@@@/  &@@@@@%   @@@@@@@    @@@@@@     @@@@@@*   #@@@@@      @@@@@. /@@@@@(     @@@@@@   @@@@@  ".light_yellow
    puts "               @@@@@@   @@@@@@,             @@@@@@(    @@@@@@   &@@@@@/    %@@@@@/  @@@@@@    (@@@@@@    @@@@@@     @@@@@@*   #@@@@@      @@@@@. /@@@@@(     @@@@@@   @@@@@  ".light_yellow
    puts "   (@@@@@%     @@@@@@   @@@@@@@@@@@@@@@@@   @@@@@@(    @@@@@@   &@@@@@@@@@@@@@@@@/  @@@@@@@@@@@@@@@@@    @@@@@@@@@@@@@@@@@.   #@@@@@      @@@@@. *@@@@@@@@@@@@@@@@@   @@@@@  ".light_yellow
    puts "   (@@@@@%     @@@@@@   @@@@@@@@@@@@@@@@@   @@@@@@(    @@@@@@   &@@@@@@@@@@@@@@@@   @@@@@@@@@@@@@@@@@/   @@@@@@@@@@@@@@@@     #@@@@@      @@@@@.  .@@@@@@@@@@@@@@@@   @@@@@  ".light_yellow
    puts "   (@@@@@%     @@@@@@   @@@@@@@             @@@@@@(    @@@@@@   &@@@@@/            #@@@@@&     @@@@@@@   @@@@@@    (@@@@@@#   #@@@@@      @@@@@.             @@@@@@          ".light_yellow
    puts "   (@@@@@%     @@@@@@   @@@@@@,             @@@@@@(    @@@@@@   &@@@@@/            @@@@@@,     @@@@@@@   @@@@@@      @@@@@@   #@@@@@      @@@@@.             @@@@@@   @@@@@  ".light_yellow
    puts "   (@@@@@%     @@@@@@   @@@@@@,             @@@@@@(    @@@@@@   &@@@@@/            @@@@@@      .@@@@@@   @@@@@@      @@@@@@.  #@@@@@      @@@@@.             @@@@@@   @@@@@  ".light_yellow
    puts "   (@@@@@@     @@@@@@   @@@@@@@             @@@@@@@   (@@@@@@   &@@@@@/            @@@@@@       @@@@@@(  @@@@@@      &@@@@@%  #@@@@@     @@@@@@.            .@@@@@@          ".light_yellow
    puts "   (@@@@@@@@@@@@@@@@@   @@@@@@@@@@@@@@@@@   @@@@@@@@@@@@@@@@@   &@@@@@/           .@@@@@@       @@@@@@@  @@@@@@      *@@@@@@  #@@@@@@@@@@@@@@@@       .@@@@@@@@@@@@          ".light_yellow
    puts "    #@@@@@@@@@@@@@@@,    /@@@@@@@@@@@@@@@    @@@@@@@@@@@@@@@.   &@@@@@/           @@@@@@/       &@@@@@@  @@@@@@       @@@@@@  #@@@@@@@@@@@@@@%        .@@@@@@@@@@,           ".light_yellow
  end

  def self.board
    puts "█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████".light_black.on_blue
    puts "█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████".light_black.on_blue
    puts "███                           █                           █                           █                           █                           █                           ███".light_black.on_blue
    puts "███                           █                           █                           █                           █                           █                           ███".light_black.on_blue
    puts "███                           █                           █                           █                           █                           █                           ███".light_black.on_blue
    puts "███".light_black.on_blue + "#{CLI.disp_cat(Category.all[0], 0)}    ".rjust(27).white.on_blue + "█".light_black.on_blue + "#{CLI.disp_cat(Category.all[1], 0)}    ".rjust(27).white.on_blue + "█".light_black.on_blue + "#{CLI.disp_cat(Category.all[2], 0)}    ".rjust(27).white.on_blue + "█".light_black.on_blue + "#{CLI.disp_cat(Category.all[3], 0)}    ".rjust(27).white.on_blue + "█".light_black.on_blue + "#{CLI.disp_cat(Category.all[4], 0)}    ".rjust(27).white.on_blue + "█".light_black.on_blue + "#{CLI.disp_cat(Category.all[5], 0)}    ".rjust(27).white.on_blue + "███".light_black.on_blue
    puts "███".light_black.on_blue + "#{CLI.disp_cat(Category.all[0], 1)}          ".rjust(27).white.on_blue + "█".light_black.on_blue + "#{CLI.disp_cat(Category.all[1], 1)}          ".rjust(27).white.on_blue + "█".light_black.on_blue + "#{CLI.disp_cat(Category.all[2], 1)}          ".rjust(27).white.on_blue + "█".light_black.on_blue + "#{CLI.disp_cat(Category.all[3], 1)}          ".rjust(27).white.on_blue + "█".light_black.on_blue + "#{CLI.disp_cat(Category.all[4], 1)}          ".rjust(27).white.on_blue + "█".light_black.on_blue + "#{CLI.disp_cat(Category.all[5], 1)}          ".rjust(27).white.on_blue + "███".light_black.on_blue
    puts "███                           █                           █                           █                           █                           █                           ███".light_black.on_blue
    puts "███                           █                           █                           █                           █                           █                           ███".light_black.on_blue
    puts "█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████".light_black.on_blue
    puts "█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████".light_black.on_blue
    puts "███                           █                           █                           █                           █                           █                           ███".light_black.on_blue
    puts "███                           █                           █                           █                           █                           █                           ███".light_black.on_blue
    puts "███                           █                           █                           █                           █                           █                           ███".light_black.on_blue
    puts "███            ".light_black.on_blue + "#{CLI.disp_points("A1")}".yellow.on_blue + "            █            ".light_black.on_blue + "#{CLI.disp_points("B1")}".yellow.on_blue + "            █            ".light_black.on_blue + "#{CLI.disp_points("C1")}".yellow.on_blue + "            █            ".light_black.on_blue + "#{CLI.disp_points("D1")}".yellow.on_blue + "            █            ".light_black.on_blue + "#{CLI.disp_points("E1")}".yellow.on_blue + "            █            ".light_black.on_blue + "#{CLI.disp_points("F1")}".yellow.on_blue + "            ███".light_black.on_blue
    puts "███                           █                           █                           █                           █                           █                           ███".light_black.on_blue
    puts "███                           █                           █                           █                           █                           █                           ███".light_black.on_blue
    puts "███           [A1]            █           [B1]            █           [C1]            █           [D1]            █           [E1]            █           [F1]            ███".light_black.on_blue
    puts "█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████".light_black.on_blue
    puts "███                           █                           █                           █                           █                           █                           ███".light_black.on_blue
    puts "███                           █                           █                           █                           █                           █                           ███".light_black.on_blue
    puts "███                           █                           █                           █                           █                           █                           ███".light_black.on_blue
    puts "███            ".light_black.on_blue + "#{CLI.disp_points("A2")}".yellow.on_blue + "            █            ".light_black.on_blue + "#{CLI.disp_points("B2")}".yellow.on_blue + "            █            ".light_black.on_blue + "#{CLI.disp_points("C2")}".yellow.on_blue + "            █            ".light_black.on_blue + "#{CLI.disp_points("D2")}".yellow.on_blue + "            █            ".light_black.on_blue + "#{CLI.disp_points("E2")}".yellow.on_blue + "            █            ".light_black.on_blue + "#{CLI.disp_points("F2")}".yellow.on_blue + "            ███".light_black.on_blue
    puts "███                           █                           █                           █                           █                           █                           ███".light_black.on_blue
    puts "███                           █                           █                           █                           █                           █                           ███".light_black.on_blue
    puts "███           [A2]            █           [B2]            █           [C2]            █           [D2]            █           [E2]            █           [F2]            ███".light_black.on_blue
    puts "█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████".light_black.on_blue
    puts "███                           █                           █                           █                           █                           █                           ███".light_black.on_blue
    puts "███                           █                           █                           █                           █                           █                           ███".light_black.on_blue
    puts "███                           █                           █                           █                           █                           █                           ███".light_black.on_blue
    puts "███            ".light_black.on_blue + "#{CLI.disp_points("A3")}".yellow.on_blue + "            █            ".light_black.on_blue + "#{CLI.disp_points("B3")}".yellow.on_blue + "            █            ".light_black.on_blue + "#{CLI.disp_points("C3")}".yellow.on_blue + "            █            ".light_black.on_blue + "#{CLI.disp_points("D3")}".yellow.on_blue + "            █            ".light_black.on_blue + "#{CLI.disp_points("E3")}".yellow.on_blue + "            █            ".light_black.on_blue + "#{CLI.disp_points("F3")}".yellow.on_blue + "            ███".light_black.on_blue
    puts "███                           █                           █                           █                           █                           █                           ███".light_black.on_blue
    puts "███                           █                           █                           █                           █                           █                           ███".light_black.on_blue
    puts "███           [A3]            █           [B3]            █           [C3]            █           [D3]            █           [E3]            █           [F3]            ███".light_black.on_blue
    puts "█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████".light_black.on_blue
    puts "███                           █                           █                           █                           █                           █                           ███".light_black.on_blue
    puts "███                           █                           █                           █                           █                           █                           ███".light_black.on_blue
    puts "███                           █                           █                           █                           █                           █                           ███".light_black.on_blue
    puts "███            ".light_black.on_blue + "#{CLI.disp_points("A4")}".yellow.on_blue + "            █            ".light_black.on_blue + "#{CLI.disp_points("B4")}".yellow.on_blue + "            █            ".light_black.on_blue + "#{CLI.disp_points("C4")}".yellow.on_blue + "            █            ".light_black.on_blue + "#{CLI.disp_points("D4")}".yellow.on_blue + "            █            ".light_black.on_blue + "#{CLI.disp_points("E4")}".yellow.on_blue + "            █            ".light_black.on_blue + "#{CLI.disp_points("F4")}".yellow.on_blue + "            ███".light_black.on_blue
    puts "███                           █                           █                           █                           █                           █                           ███".light_black.on_blue
    puts "███                           █                           █                           █                           █                           █                           ███".light_black.on_blue
    puts "███           [A4]            █           [B4]            █           [C4]            █           [D4]            █           [E4]            █           [F4]            ███".light_black.on_blue
    puts "█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████".light_black.on_blue
    puts "███                           █                           █                           █                           █                           █                           ███".light_black.on_blue
    puts "███                           █                           █                           █                           █                           █                           ███".light_black.on_blue
    puts "███                           █                           █                           █                           █                           █                           ███".light_black.on_blue
    puts "███           ".light_black.on_blue + "#{CLI.disp_points("A5")}".yellow.on_blue + "            █           ".light_black.on_blue + "#{CLI.disp_points("B5")}".yellow.on_blue + "            █           ".light_black.on_blue + "#{CLI.disp_points("C5")}".yellow.on_blue + "            █           ".light_black.on_blue + "#{CLI.disp_points("D5")}".yellow.on_blue + "            █           ".light_black.on_blue + "#{CLI.disp_points("E5")}".yellow.on_blue + "            █           ".light_black.on_blue + "#{CLI.disp_points("F5")}".yellow.on_blue + "            ███".light_black.on_blue
    puts "███                           █                           █                           █                           █                           █                           ███".light_black.on_blue
    puts "███                           █                           █                           █                           █                           █                           ███".light_black.on_blue
    puts "███           [A5]            █           [B5]            █           [C5]            █           [D5]            █           [E5]            █           [F5]            ███".light_black.on_blue
    puts "█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████".light_black.on_blue
    puts ""
  end
  
  def self.daily_double_art
    24.times {puts ""}
    puts "                                                             _______       ___       __   __      ____    ____                                                              ".white.on_blue
    puts "                                                            |       \\     /   \\     |  | |  |     \\   \\  /   /                                                              ".white.on_blue
    puts "                                                            |  .--.  |   /  ^  \\    |  | |  |      \\   \\/   /                                                               ".white.on_blue
    puts "                                                            |  |  |  |  /  /_\\  \\   |  | |  |       \\_    _/                                                                ".white.on_blue
    puts "                                                            |  '--'  | /  _____  \\  |  | |  `----.    |  |                                                                  ".white.on_blue
    puts "                                                            |_______/ /__/     \\__\\ |__| |_______|    |__|                                                                  ".white.on_blue
    puts "                                                         _______    ______    __    __  .______    __       _______                                                         ".white.on_blue
    puts "                                                        |       \\  /  __  \\  |  |  |  | |   _  \\  |  |     |   ____|                                                        ".white.on_blue
    puts "                                                        |  .--.  ||  |  |  | |  |  |  | |  |_)  | |  |     |  |__                                                           ".white.on_blue
    puts "                                                        |  |  |  ||  |  |  | |  |  |  | |   _  <  |  |     |   __|                                                          ".white.on_blue
    puts "                                                        |  '--'  ||  `--'  | |  `--'  | |  |_)  | |  `----.|  |____                                                         ".white.on_blue
    puts "                                                        |_______/  \\______/   \\______/  |______/  |_______||_______|                                                        ".white.on_blue
    puts "                                                                                                                                                                            ".white.on_blue
    23.times {puts ""}
  end

end